<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Alexis Salim" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 1</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project1/">Project 1</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              
<script src="../../rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="../../rmarkdown-libs/plotly-binding/plotly.js"></script>
<script src="../../rmarkdown-libs/typedarray/typedarray.min.js"></script>
<script src="../../rmarkdown-libs/jquery/jquery.min.js"></script>
<link href="../../rmarkdown-libs/crosstalk/css/crosstalk.css" rel="stylesheet" />
<script src="../../rmarkdown-libs/crosstalk/js/crosstalk.min.js"></script>
<link href="../../rmarkdown-libs/plotly-htmlwidgets-css/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="../../rmarkdown-libs/plotly-main/plotly-latest.min.js"></script>


<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>The first dataset that I have chosen to examine for this project is the “pwt_sample” dataset, which has 1,428 observations and 7 variables. The dataset gives macroeconomic data for 21 countries. The variables are country, the country’s ISO code, year, population in millions, human capital index, real GDP at 2011 prices, and a share of labor compensation in GDP. The second dataset that I have chosen to examine is the “ghp100k” dataset, which has 561 observations and 3 variables. This dataset provides estimates of the yearly rate of gun homicides per 100,000 people in the population of certain countries. The variables are country, year, and an estimated rate of gun homicide per 100,000 people.</p>
<p>Both of these datasets were found using “<a href="https://vincentarelbundock.github.io/Rdatasets/datasets.html" class="uri">https://vincentarelbundock.github.io/Rdatasets/datasets.html</a>” provided in the project instructions. Personally, after looking for the common variable I wanted to explore (country) by using Ctrl+F, I thought that these two datasets would be interesting to look at for potential correlations. It is possible that I will find an association between GDP and gun homicide rates, but I do not know whether the relationship will be positive or negative.</p>
<pre class="r"><code># install.packages(&#39;stevedata&#39;)
library(stevedata)
library(tidyverse)
glimpse(pwt_sample)  #economic data for countries</code></pre>
<pre><code>## Rows: 1,428
## Columns: 7
## $ country &lt;chr&gt; &quot;Australia&quot;, &quot;Australia&quot;, &quot;Australia&quot;, &quot;Australia&quot;, &quot;Australi…
## $ isocode &lt;chr&gt; &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;…
## $ year    &lt;dbl&gt; 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1…
## $ pop     &lt;dbl&gt; 8.386674, 8.633449, 8.816668, 8.985786, 9.194855, 9.411000, 9…
## $ hc      &lt;dbl&gt; 2.667302, 2.674344, 2.681403, 2.688482, 2.695580, 2.702696, 2…
## $ rgdpna  &lt;dbl&gt; 119510.4, 122550.0, 117533.8, 130284.5, 140700.2, 146249.9, 1…
## $ labsh   &lt;dbl&gt; 0.6804925, 0.6804925, 0.6804925, 0.6804925, 0.6804925, 0.6804…</code></pre>
<pre class="r"><code>glimpse(ghp100k)  #gun homicides per 100k people in different countries</code></pre>
<pre><code>## Rows: 561
## Columns: 3
## $ country &lt;chr&gt; &quot;Australia&quot;, &quot;Australia&quot;, &quot;Australia&quot;, &quot;Australia&quot;, &quot;Australi…
## $ year    &lt;dbl&gt; 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1…
## $ value   &lt;dbl&gt; 0.74, 0.48, 0.46, 0.49, 0.55, 0.36, 0.43, 0.37, 0.57, 0.43, 0…</code></pre>
</div>
<div id="joiningmerging" class="section level2">
<h2>Joining/Merging</h2>
<p>In this section, I am joining the “pwt_sample” and “ghp100k” datasets into a dataset named “joined”. I chose to use “inner_join” because I would like to look at the gun homicide data in relation to other variables, and doing an inner join allows for all NAs to be eliminated, and only keeps the data with a match in both datasets. Rows were dropped from both datasets: “pwt_sample” started with 1,428 rows and “ghp100k” started with 561 rows. These were narrowed down to 403 rows after the joining.</p>
<pre class="r"><code>joined &lt;- inner_join(pwt_sample, ghp100k) %&gt;% glimpse()</code></pre>
<pre><code>## Rows: 403
## Columns: 8
## $ country &lt;chr&gt; &quot;Australia&quot;, &quot;Australia&quot;, &quot;Australia&quot;, &quot;Australia&quot;, &quot;Australi…
## $ isocode &lt;chr&gt; &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;, &quot;AUS&quot;…
## $ year    &lt;dbl&gt; 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1…
## $ pop     &lt;dbl&gt; 16.52743, 16.79229, 17.04143, 17.27187, 17.48595, 17.68748, 1…
## $ hc      &lt;dbl&gt; 3.370583, 3.390770, 3.411077, 3.423623, 3.436215, 3.448854, 3…
## $ rgdpna  &lt;dbl&gt; 503555.0, 524450.1, 523807.9, 525471.7, 547202.6, 569298.2, 5…
## $ labsh   &lt;dbl&gt; 0.6090810, 0.6184667, 0.6260087, 0.6173111, 0.6072758, 0.6013…
## $ value   &lt;dbl&gt; 0.74, 0.48, 0.46, 0.49, 0.55, 0.36, 0.43, 0.37, 0.57, 0.43, 0…</code></pre>
<pre class="r"><code>head(joined)</code></pre>
<pre><code>## # A tibble: 6 x 8
##   country   isocode  year   pop    hc  rgdpna labsh value
##   &lt;chr&gt;     &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Australia AUS      1988  16.5  3.37 503555  0.609  0.74
## 2 Australia AUS      1989  16.8  3.39 524450. 0.618  0.48
## 3 Australia AUS      1990  17.0  3.41 523808. 0.626  0.46
## 4 Australia AUS      1991  17.3  3.42 525472. 0.617  0.49
## 5 Australia AUS      1992  17.5  3.44 547203. 0.607  0.55
## 6 Australia AUS      1993  17.7  3.45 569298. 0.601  0.36</code></pre>
</div>
<div id="wrangling" class="section level2">
<h2>Wrangling</h2>
<p>For the first line of code, I first selected the columns that were of most interest to me. I then arranged the columns by country. Finally, I filtered the data so I could just look at the information for Canada. In the second line of code, I created a new variable called “gunhomic”, which displays the actual number of people killed by gun violence; this variable was added to my “joined” dataset. For the third line of code, I assessed the average gun homicide rate, average number of actual gun homicides, and average populations for each country along with counting the number of entries per country; I then arranged this data from greatest to least by average rate of gun homicides and rounded all the numeric variables to the hundredth place. In the fourth line of code, I generate summary statistics for the variables rgdpna, hc, labsh, and year.</p>
<p>Some interesting statistics to note are that Canada has the highest average rate of gun homicides out of 100k people (.71), while the United Kingdom has the lowest average rate of gun homicide out of 100k people (.06). Additionally, from the third line of code, I can determine that are 18 different countries in the “joined” dataset. From the summary statistics created in the fourth line of code, I can determine that the range of years for the dataset is from 1974 to 2017.</p>
<pre class="r"><code>joined %&gt;% select(country, isocode, year, value, everything()) %&gt;% 
    arrange(country) %&gt;% filter(isocode == &quot;CAN&quot;)</code></pre>
<pre><code>## # A tibble: 44 x 8
##    country isocode  year value   pop    hc  rgdpna labsh
##    &lt;chr&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
##  1 Canada  CAN      1974  1.24  22.8  2.93 559210. 0.748
##  2 Canada  CAN      1975  1.26  23.2  2.96 569404. 0.731
##  3 Canada  CAN      1976  1.1   23.5  2.98 599009. 0.732
##  4 Canada  CAN      1977  1.09  23.7  3.01 619724  0.725
##  5 Canada  CAN      1978  1.04  24.0  3.03 644225. 0.709
##  6 Canada  CAN      1979  0.85  24.3  3.06 668738. 0.684
##  7 Canada  CAN      1980  0.79  24.5  3.09 683200. 0.671
##  8 Canada  CAN      1981  0.8   24.8  3.11 707133. 0.693
##  9 Canada  CAN      1982  0.99  25.0  3.13 684491. 0.707
## 10 Canada  CAN      1983  0.88  25.3  3.15 702278. 0.677
## # … with 34 more rows</code></pre>
<pre class="r"><code>joined &lt;- joined %&gt;% mutate(gunhomic = value * 10 * pop)</code></pre>
<pre class="r"><code>joined %&gt;% group_by(isocode) %&gt;% summarize(avgrate = mean(value), 
    avggunhomic = mean(gunhomic), meanpop = mean(pop), count = n()) %&gt;% 
    arrange(desc(avgrate)) %&gt;% mutate_if(is.numeric, round, 2)</code></pre>
<pre><code>## # A tibble: 18 x 5
##    isocode avgrate avggunhomic meanpop count
##    &lt;chr&gt;     &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;
##  1 CAN       0.71       201.     29.5     44
##  2 PRT       0.63        65.4    10.4     21
##  3 ITA       0.59       340.     58.6     21
##  4 BEL       0.48        49.8    10.6     21
##  5 GRC       0.48        53.6    11.2     19
##  6 FIN       0.45        23.4     5.28    21
##  7 NLD       0.35        57.2    16.3     22
##  8 CHE       0.32        23.9     7.58    24
##  9 IRL       0.32        13.7     4.2     18
## 10 AUS       0.290       54.8    19.9     29
## 11 FRA       0.23       146.     63.3     19
## 12 SWE       0.21        19.7     9.17    23
## 13 DNK       0.2         10.8     5.42    23
## 14 DEU       0.2        161.     81.4     22
## 15 ESP       0.2         83.9    43.5     22
## 16 AUT       0.16        13.7     8.35    18
## 17 ISL       0.13         0.37    0.31    16
## 18 GBR       0.06        35.9    61.2     20</code></pre>
<pre class="r"><code>summarystats &lt;- joined %&gt;% summarize(mean(rgdpna), median(hc), 
    sd(labsh), min(year), max(year))
summarystats</code></pre>
<pre><code>## # A tibble: 1 x 5
##   `mean(rgdpna)` `median(hc)` `sd(labsh)` `min(year)` `max(year)`
##            &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
## 1        907791.         3.19      0.0545        1974        2017</code></pre>
</div>
<div id="tidying-rearranging" class="section level2">
<h2>Tidying: Rearranging</h2>
<p>To utilize the “pivot_wider” function, I first removed the columns that I was not interested in using the “select” function. I then created columns for each different isocode and used values from the “year” column. I renamed this dataset “widerjoin” and took a slice to observe the results and number of rows/columns.</p>
<p>To utilize the “pivot_longer” function, I selected the columns with the isocodes as names and put those in a new “country code” column. I then used the values from these columns and placed them in a column called “year”. I then omitted NAs from the table. This gave me back the data from before using “pivot_wider” in the first line of code in this section.</p>
<pre class="r"><code>widerjoin &lt;- joined %&gt;% select(-hc, -rgdpna, -labsh, -country) %&gt;% 
    pivot_wider(names_from = &quot;isocode&quot;, values_from = &quot;year&quot;)
widerjoin %&gt;% slice(1:15)</code></pre>
<pre><code>## # A tibble: 15 x 21
##      pop value gunhomic   AUS   AUT   BEL   CAN   CHE   DEU   DNK   ESP   FIN
##    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
##  1  16.5 0.74     122.   1988    NA    NA    NA    NA    NA    NA    NA    NA
##  2  16.8 0.48      80.6  1989    NA    NA    NA    NA    NA    NA    NA    NA
##  3  17.0 0.46      78.4  1990    NA    NA    NA    NA    NA    NA    NA    NA
##  4  17.3 0.49      84.6  1991    NA    NA    NA    NA    NA    NA    NA    NA
##  5  17.5 0.55      96.2  1992    NA    NA    NA    NA    NA    NA    NA    NA
##  6  17.7 0.36      63.7  1993    NA    NA    NA    NA    NA    NA    NA    NA
##  7  17.9 0.43      76.9  1994    NA    NA    NA    NA    NA    NA    NA    NA
##  8  18.1 0.37      66.9  1995    NA    NA    NA    NA    NA    NA    NA    NA
##  9  18.3 0.570    104.   1996    NA    NA    NA    NA    NA    NA    NA    NA
## 10  18.5 0.43      79.4  1997    NA    NA    NA    NA    NA    NA    NA    NA
## 11  18.7 0.3       56.0  1998    NA    NA    NA    NA    NA    NA    NA    NA
## 12  18.9 0.26      49.0  1999    NA    NA    NA    NA    NA    NA    NA    NA
## 13  19.1 0.3       57.2  2000    NA    NA    NA    NA    NA    NA    NA    NA
## 14  19.3 0.24      46.2  2001    NA    NA    NA    NA    NA    NA    NA    NA
## 15  19.5 0.23      44.8  2002    NA    NA    NA    NA    NA    NA    NA    NA
## # … with 9 more variables: FRA &lt;dbl&gt;, GBR &lt;dbl&gt;, GRC &lt;dbl&gt;, IRL &lt;dbl&gt;,
## #   ISL &lt;dbl&gt;, ITA &lt;dbl&gt;, NLD &lt;dbl&gt;, PRT &lt;dbl&gt;, SWE &lt;dbl&gt;</code></pre>
<pre class="r"><code>widerjoin %&gt;% pivot_longer(4:21, names_to = &quot;country code&quot;, values_to = &quot;year&quot;) %&gt;% 
    na.omit()</code></pre>
<pre><code>## # A tibble: 403 x 5
##      pop value gunhomic `country code`  year
##    &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;
##  1  16.5 0.74     122.  AUS             1988
##  2  16.8 0.48      80.6 AUS             1989
##  3  17.0 0.46      78.4 AUS             1990
##  4  17.3 0.49      84.6 AUS             1991
##  5  17.5 0.55      96.2 AUS             1992
##  6  17.7 0.36      63.7 AUS             1993
##  7  17.9 0.43      76.9 AUS             1994
##  8  18.1 0.37      66.9 AUS             1995
##  9  18.3 0.570    104.  AUS             1996
## 10  18.5 0.43      79.4 AUS             1997
## # … with 393 more rows</code></pre>
</div>
<div id="visualizing" class="section level2">
<h2>Visualizing</h2>
<pre class="r"><code>cormat &lt;- joined %&gt;% select(humancap = &quot;hc&quot;, laborshare = &quot;labsh&quot;, 
    realgdp = &quot;rgdpna&quot;, everything()) %&gt;% select_if(is.numeric) %&gt;% 
    cor(use = &quot;pair&quot;) %&gt;% round(2)
cormat</code></pre>
<pre><code>##            humancap laborshare realgdp  year   pop value gunhomic
## humancap       1.00       0.15    0.28  0.21  0.17 -0.35    -0.12
## laborshare     0.15       1.00    0.06 -0.36  0.07  0.25     0.14
## realgdp        0.28       0.06    1.00  0.10  0.98 -0.16     0.45
## year           0.21      -0.36    0.10  1.00  0.01 -0.61    -0.37
## pop            0.17       0.07    0.98  0.01  1.00 -0.11     0.50
## value         -0.35       0.25   -0.16 -0.61 -0.11  1.00     0.62
## gunhomic      -0.12       0.14    0.45 -0.37  0.50  0.62     1.00</code></pre>
<pre class="r"><code>cormat %&gt;% as.data.frame</code></pre>
<pre><code>##            humancap laborshare realgdp  year   pop value gunhomic
## humancap       1.00       0.15    0.28  0.21  0.17 -0.35    -0.12
## laborshare     0.15       1.00    0.06 -0.36  0.07  0.25     0.14
## realgdp        0.28       0.06    1.00  0.10  0.98 -0.16     0.45
## year           0.21      -0.36    0.10  1.00  0.01 -0.61    -0.37
## pop            0.17       0.07    0.98  0.01  1.00 -0.11     0.50
## value         -0.35       0.25   -0.16 -0.61 -0.11  1.00     0.62
## gunhomic      -0.12       0.14    0.45 -0.37  0.50  0.62     1.00</code></pre>
<pre class="r"><code>tidycorr &lt;- cormat %&gt;% as.data.frame %&gt;% rownames_to_column(&quot;var1&quot;) %&gt;% 
    pivot_longer(-1, names_to = &quot;var2&quot;, values_to = &quot;correlation&quot;)
tidycorr</code></pre>
<pre><code>## # A tibble: 49 x 3
##    var1       var2       correlation
##    &lt;chr&gt;      &lt;chr&gt;            &lt;dbl&gt;
##  1 humancap   humancap          1   
##  2 humancap   laborshare        0.15
##  3 humancap   realgdp           0.28
##  4 humancap   year              0.21
##  5 humancap   pop               0.17
##  6 humancap   value            -0.35
##  7 humancap   gunhomic         -0.12
##  8 laborshare humancap          0.15
##  9 laborshare laborshare        1   
## 10 laborshare realgdp           0.06
## # … with 39 more rows</code></pre>
<pre class="r"><code>tidycorr %&gt;% ggplot(aes(var1, var2, fill = correlation)) + geom_tile() + 
    scale_fill_gradient2(low = &quot;red&quot;, mid = &quot;white&quot;, high = &quot;blue&quot;) + 
    geom_text(aes(label = round(correlation, 2)), color = &quot;black&quot;, 
        size = 4) + theme(axis.text.x = element_text(angle = 90, 
    hjust = 1)) + coord_fixed() + ggtitle(&quot;Correlation Heatmap&quot;)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-7-1.png" width="672" style="display: block; margin: auto;" />
From the resulting correlation heatmap from the code chunk below, I can see that population and real GDP are highly positively correlated(.98). I can also see that year and value (estimate of gun homicide rate) are decently negatively correlated (-.61). Interestingly, there is almost no correlation between year and population; I expected that population would increase as the years increased.</p>
<pre class="r"><code>library(ggplot2)
joined %&gt;% ggplot(aes(year, rgdpna)) + geom_bar(stat = &quot;summary&quot;) + 
    geom_line(aes(color = isocode)) + scale_color_manual(values = rainbow(18)) + 
    scale_y_continuous(&quot;Real GDP (million USD in 2011)&quot;, breaks = seq(0, 
        4e+06, 5e+05)) + scale_x_continuous(&quot;Year&quot;, breaks = seq(1970, 
    2020, 5)) + ggtitle(&quot;National GDP Over Time&quot;)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-8-1.png" width="672" style="display: block; margin: auto;" />
In this plot, the bars show that the average GDP for all countries tends to increase gradually over time; however, based on the individual lines, differences in individual countries’ trends are more apparent. Based on the individual lines, for almost all the countries the real GDP trends up over time (with some exceptions).</p>
<pre class="r"><code>joined %&gt;% ggplot(aes(year, value, color = isocode)) + geom_point(aes(shape = isocode)) + 
    scale_shape_manual(values = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 
        10, 11, 12, 13, 14, 15, 16, 17, 18)) + geom_smooth(method = lm, 
    se = F) + scale_y_continuous(&quot;Estimated Homicide Rate (per 100k people)&quot;, 
    breaks = seq(0, 1.7, 0.1)) + scale_x_continuous(&quot;Year&quot;, breaks = seq(1970, 
    2020, 5)) + ggtitle(&quot;National Gun Homicide Rate Over Time&quot;)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-9-1.png" width="672" style="display: block; margin: auto;" />
In this plot, one can see the trends of gun homicide rates over time and per country. The discrete points are plotted using different shapes and colors for each country, while lines of best fit were also created and colored based on country. For most of these countries, gun homicides have decreased over time.</p>
</div>
<div id="dimensionality-reduction" class="section level2">
<h2>Dimensionality Reduction</h2>
<pre class="r"><code>library(cluster)
library(plotly)
pam_dat &lt;- joined %&gt;% select_if(is.numeric)
sil_width &lt;- vector()
for (i in 2:10) {
    pam_fit &lt;- pam(pam_dat, k = i)
    sil_width[i] &lt;- pam_fit$silinfo$avg.width
}
ggplot() + geom_line(aes(x = 1:10, y = sil_width)) + scale_x_continuous(name = &quot;k&quot;, 
    breaks = 1:10)</code></pre>
<p><img src="../../project/project1_files/figure-html/unnamed-chunk-10-1.png" width="672" style="display: block; margin: auto;" />
Based on this graph, it appears that choosing 4 clusters is better than 3 since the silhouette width is higher.</p>
<p>Below is the code used for PAM clustering of the dataset using numeric variables and 4 clusters.</p>
<pre class="r"><code>pam &lt;- joined %&gt;% select_if(is.numeric) %&gt;% pam(4)
pam</code></pre>
<pre><code>## Medoids:
##       ID year      pop       hc    rgdpna     labsh value  gunhomic
## [1,] 269 2002 11.21680 2.770473  267030.1 0.5391746  0.30  33.65040
## [2,]  89 1994 29.02619 3.374395  939178.6 0.6954579  0.67 194.47546
## [3,] 325 2003 58.14704 2.837316 2103585.2 0.5057539  0.60 348.88223
## [4,] 148 2005 81.67123 3.609564 3149246.8 0.6075891  0.11  89.83836
## Clustering vector:
##   [1] 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1
##  [38] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2
##  [75] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
##  [ reached getOption(&quot;max.print&quot;) -- omitted 303 entries ]
## Objective function:
##    build     swap 
## 171122.4 156176.1 
## 
## Available components:
##  [1] &quot;medoids&quot;    &quot;id.med&quot;     &quot;clustering&quot; &quot;objective&quot;  &quot;isolation&quot; 
##  [6] &quot;clusinfo&quot;   &quot;silinfo&quot;    &quot;diss&quot;       &quot;call&quot;       &quot;data&quot;</code></pre>
<pre class="r"><code>final &lt;- joined %&gt;% mutate(cluster = pam$clustering)
final %&gt;% plot_ly(x = ~rgdpna, y = ~pop, z = ~value, color = ~cluster, 
    type = &quot;scatter3d&quot;, mode = &quot;markers&quot;)</code></pre>
<p><div id="htmlwidget-1" style="width:672px;height:480px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"visdat":{"d3f44275f8b6":["function () ","plotlyVisDat"]},"cur_data":"d3f44275f8b6","attrs":{"d3f44275f8b6":{"x":{},"y":{},"z":{},"mode":"markers","color":{},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter3d"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"scene":{"xaxis":{"title":"rgdpna"},"yaxis":{"title":"pop"},"zaxis":{"title":"value"}},"hovermode":"closest","showlegend":false,"legend":{"yanchor":"top","y":0.5}},"source":"A","config":{"showSendToCloud":false},"data":[{"x":[503555,524450.0625,523807.90625,525471.6875,547202.5625,569298.1875,590548.25,613845.0625,638192.75,667401.1875,700891.8125,728529.3125,742612.5,772339.5,795399.5625,827224.3125,853615.375,877808.875,910966.5625,944287.625,962443.6875,982202.125,1006276.875,1045440.625,1073034.875,1100486.625,1126360.625,1158206.375,1180879.125,286293.125,295957.5625,299707.875,304657.6875,307525.96875,315937.15625,323027,334184.46875,346640.9375,351703.34375,338463.1875,344681.09375,354755.40625,357169.34375,357260.4375,359622.90625,363733.3125,371151.9375,284538.71875,291359.9375,300762.03125,307934.46875,312841.09375,324448.8125,330857.5625,342647.125,367174.875,380521.15625,388490.28125,398226.375,411961.125,415187.4375,405832.53125,416969.53125,424467.90625,425464.46875,426318.21875,431667.125,439077.46875,559209.625,569403.875,599008.875,619724,644225.375,668737.625,683199.875,707133.1875,684490.5625,702277.5625,743890,779106.375,795949.1875,828555,865255,885363.3125,886729.8125,867880.6875,875543.875,898791.625,939178.5625,964327.0625,979862.8125,1021799.125,1061462.875,1116268.5,1174121.125,1194912.75,1230879.875,1253063.625,1291732.75,1333086,1368058.375,1396277.875,1410245.75,1368649.375,1410851.875,1455169.75,1480569.375,1517213.5,1560541.125,1576160.25,1598448.875,1647159.125,348479.40625,350155.125,352046.0625,360284.4375,371056.5625,377344.9375,392200.34375,397347.65625,397993.8125,398151.3125,409204.90625,421952.625,438782.78125,456825,466668.21875,456298.34375,469999.59375,477955.8125,482764.15625,491705.125,503748.0625,510464.875,518638.5625,527023.375,2736379,2783927.5,2806697,2858598.5,2915188,2973116.5,3061181.75,3113083.25,3113083.25,3090983.25,3127146.75,3149246.75,3265774,3372255.5,3408754,3217221,3348481.5,3471035.75,3488113,3505190.25,3581535.75,3643817.5,180737.9375,190375.6875,196139.578125,201827.75,208409.109375,213031.96875,219312.15625,227529.578125,229402.484375,230472.28125,231371.296875,237544.734375,243095.359375,252607.625,254904.46875,253599.296875,241156.375,245668.40625,248952.4375,249516.234375,251845.09375,255923.40625,261918.71875,922462.25,970489.375,996447.875,1033212.875,1077702.875,1126035.375,1185592.625,1233029,1268538.75,1308974.25,1350426.125,1400702.625,1459169.625,1514165.625,1531089.25,1476371.875,1476579.625,1461832,1419033.25,1394828.75,1414077.25,1465615.875,130159.09375,140600.078125,149390.125,157499.796875,164499.296875,173768.578125,178253.1875,181248.421875,184862.484375,192120.28125,197461.140625,205468.578125,216121.71875,217679.25,199679.265625,205654.34375,210941.34375,207932.921875,206356.71875,205053.09375,205330.09375,1765489.625,1870866.125,1938005.125,2004311.5,2082954,2124274,2148395.75,2166080.5,2227375.25,2264421.5,2319884.5,2376135.5,2382193.5,2313745.5,2358850.5,2410573,2418121.5,2432057.75,2455312.5,1628056.125,1697951.125,1754684.375,1811077.375,1873622.25,1926846.125,1975012.125,2040966.75,2088884.375,2154657.5,2209560,2265804.25,2257967.75,2162080.75,2199078.5,2235248.25,2267593.75,2313996.75,2382203.25,2438164,202069.21875,230369.5625,237447.890625,246755.296875,256950.265625,267030.09375,282503.25,296800.96875,298579.21875,315456.21875,325783.4375,324691.5,310727.375,293703.78125,266881.28125,247397.640625,239378.421875,241149.296875,240093.46875,83724.203125,103020.5,111065.65625,122494.2578125,132906.515625,147018.453125,186825.21875,199307.421875,211278.53125,222944.59375,234557.265625,225325.265625,214899.9375,218771.703125,225302.015625,225385.71875,229079.390625,248158,7356.4990234375,9225.970703125,9869.8662109375,10663.62109375,11338.6279296875,11933.7724609375,13051.4091796875,13311.390625,12409.2490234375,11982.8828125,12208.353515625,12366.62890625,12877.8466796875,13145.7421875,13733.076171875,14742.66015625,1789608.75,1888826.5,1923493.375,1954578.5,1985067,2058715.125,2095199.375,2100407,2103585.25,2136862.75,2157155.75,2200441,2232872.5,2209418.5,2088296.875,2123516.5,2135761.25,2075553.75,2039684.875,2042003.375,2060871.375,507684,542175.5,565488.3125,591079,620938.5,647258.625,661008.125,661693.125,663571.8125,677047,691673.6875,716011.1875,742492.6875,755108.0625,726658.75,736851.3125,749109.75,741191.375,739780.625,750283.25,767245.3125,784201,197081.484375,205522.046875,212708.5,222123.421875,232767.078125,241817.5625,250976.375,255853.625,257820.609375,255412.03125,260039.03125,262032.984375,266102.5,272733.78125,273277.25,265138.78125,270172.9375,265237.28125,254552.84375,251676,253923.9375,245499.703125,265807.8125,269845.53125,277704.25,289481.5625,302469.75,316823.78125,321808.84375,328487.34375,336238.90625,350733.4375,360612.46875,377559.65625,390427.28125,388252.375,368079.15625,390134.34375,400586.9375,399391.125,404337,414857.4375,433345.875,444976.71875],"y":[16.5274295806885,16.792293548584,17.041431427002,17.2718734741211,17.4859485626221,17.687479019165,17.8827362060547,18.0767421722412,18.2716846466064,18.4675884246826,18.6650447845459,18.8641128540039,19.0658378601074,19.268533706665,19.475191116333,19.6969718933105,19.948429107666,20.2389030456543,20.5736064910889,20.9466648101807,21.342493057251,21.7390403747559,22.1200637817383,22.4797992706299,22.821849822998,23.150728225708,23.4746685028076,23.7995567321777,24.1258487701416,8.05111312866211,8.06927585601807,8.09774780273438,8.13441181182861,8.17585182189941,8.21680545806885,8.25364971160889,8.28473472595215,8.31178283691406,8.33845329284668,8.37003803253174,8.40994930267334,8.45986366271973,8.51754760742188,8.57778167724609,8.63321971893311,8.67865657806396,8.71213722229004,10.0065441131592,10.1186742782593,10.1559190750122,10.1863050460815,10.2082748413086,10.2237892150879,10.2372989654541,10.2551603317261,10.4190320968628,10.4801168441772,10.5468864440918,10.6195669174194,10.6978349685669,10.7791728973389,10.8602895736694,10.938738822937,11.0130834579468,11.083550453186,11.1515121459961,11.2191610336304,11.2879400253296,22.8381900787354,23.1562099456787,23.456506729126,23.7415885925293,24.0140819549561,24.2780475616455,24.5374221801758,24.7911396026611,25.0409488677979,25.2968406677246,25.5716724395752,25.8739490509033,26.208080291748,26.5697650909424,26.9478416442871,27.3261661529541,27.6926803588867,28.044605255127,28.384349822998,28.7113037109375,29.0261878967285,29.3300724029541,29.6221313476562,29.9031505584717,30.1781349182129,30.4538841247559,30.7357730865479,31.0247325897217,31.3208885192871,31.6278057098389,31.9494171142578,32.2879791259766,32.6454811096191,33.0199317932129,33.4045486450195,33.7898292541504,34.1686668395996,34.5386238098145,34.9007034301758,35.2554931640625,35.6047286987305,35.9497108459473,36.2898216247559,36.6241989135742,6.96126317977905,7.01852512359619,7.06117296218872,7.0917649269104,7.1151270866394,7.13846397399902,7.16725015640259,7.20268487930298,7.24391412734985,7.29189300537109,7.34724712371826,7.41030788421631,7.48140716552734,7.56035804748535,7.64611291885376,7.73716115951538,7.83197116851807,7.93042087554932,8.03166961669922,8.13267421722412,8.22962856292725,8.31976890563965,8.4017391204834,8.4760046005249,80.931037902832,81.2406005859375,81.4263381958008,81.4998626708984,81.4992294311523,81.4816131591797,81.4877548217773,81.5358505249023,81.6118698120117,81.6864929199219,81.7156600952148,81.6712341308594,81.5403518676758,81.3444595336914,81.1309432983398,80.9656143188477,80.8947830200195,80.9339828491211,81.0662307739258,81.26513671875,81.4896621704102,81.7077865600586,5.19074201583862,5.21133422851562,5.23270416259766,5.25485992431641,5.27771091461182,5.30037879943848,5.32177400588989,5.34119415283203,5.35806179046631,5.37280082702637,5.38696813583374,5.40276098251343,5.42170190811157,5.44430303573608,5.46995687484741,5.49779510498047,5.52644681930542,5.55484390258789,5.58287286758423,5.61066007614136,5.63781690597534,5.6639142036438,5.68869495391846,39.6386337280273,39.8904991149902,40.0093231201172,40.1315612792969,40.2926406860352,40.539722442627,40.9037094116211,41.3921012878418,41.9855194091797,42.6534042358398,43.3516693115234,44.0426330566406,44.7255325317383,45.3938598632812,45.9978065490723,46.4760704040527,46.788631439209,46.9091377258301,46.8574028015137,46.6975517272949,46.5218276977539,46.3976631164551,5.09709692001343,5.13697910308838,5.15174579620361,5.16424179077148,5.17592620849609,5.18795394897461,5.20047903060913,5.2133731842041,5.2271032333374,5.24218511581421,5.25892686843872,5.27756977081299,5.29801416397095,5.31990194320679,5.34264612197876,5.36578178405762,5.38924217224121,5.41298007965088,5.43661594390869,5.459716796875,5.48196601867676,59.6675910949707,60.5302810668945,60.8334121704102,61.1463966369629,61.4700584411621,61.8044548034668,62.1492881774902,62.5045204162598,62.8697967529297,63.2440223693848,63.6279525756836,64.0190582275391,64.4090881347656,64.7872314453125,65.1457824707031,65.4811172485352,65.7951278686523,66.0925598144531,66.3808517456055,58.1567459106445,58.3466720581055,58.5449371337891,58.7467269897461,58.9508476257324,59.149341583252,59.3489532470703,59.5802230834961,59.8841285705566,60.2867546081543,60.8027992248535,61.4146614074707,62.0762214660645,62.7226066589355,63.3068428039551,63.811882019043,64.2503280639648,64.64111328125,65.0156860351562,65.3970794677734,10.6848182678223,11.0303926467896,11.0902662277222,11.1421194076538,11.1843976974487,11.2167987823486,11.2435674667358,11.2704763412476,11.3012037277222,11.3387699127197,11.3808965682983,11.4196472167969,11.4438276290894,11.4460048675537,11.4228048324585,11.3782567977905,11.3212995529175,11.2647256851196,11.2178001403809,3.57637500762939,3.65154504776001,3.67984890937805,3.71246409416199,3.75057005882263,3.79569888114929,4.04954719543457,4.12874889373779,4.21297693252563,4.30336999893188,4.39807319641113,4.48958921432495,4.56806421279907,4.62692785263062,4.66257905960083,4.67811679840088,4.68196678161621,4.68634700775146,0.270150005817413,0.280434995889664,0.28795200586319,0.29110398888588,0.294979006052017,0.299728006124496,0.305200010538101,0.31088399887085,0.316085994243622,0.320327997207642,0.323417991399765,0.325525999069214,0.32702898979187,0.328458994626999,0.330242991447449,0.332473993301392,57.1888885498047,57.2296714782715,57.1849021911621,57.1535530090332,57.179988861084,57.2937202453613,57.5063667297363,57.8017616271973,58.1470375061035,58.4947052001953,58.8084831237793,59.0798683166504,59.3135108947754,59.502384185791,59.6418533325195,59.729808807373,59.7599296569824,59.7338333129883,59.6679992675781,59.5856666564941,59.5042114257812,15.369119644165,15.5632553100586,15.6554746627808,15.7456474304199,15.8355226516724,15.9261884689331,16.0181140899658,16.1103553771973,16.2009506225586,16.287181854248,16.3671588897705,16.440221786499,16.5070552825928,16.568733215332,16.6269264221191,16.6829166412354,16.7370014190674,16.7890949249268,16.8396987915039,16.8893566131592,16.9384994506836,16.9873294830322,10.103443145752,10.1497354507446,10.1923942565918,10.2328844070435,10.2722864151001,10.3126106262207,10.3551168441772,10.3993120193481,10.4436683654785,10.4871129989624,10.5282678604126,10.5657234191895,10.5999507904053,10.6301202774048,10.6520986557007,10.6606159210205,10.6523208618164,10.6253299713135,10.5818214416504,10.5276737213135,10.4711675643921,8.74677562713623,8.8364200592041,8.85919094085693,8.86885261535645,8.87084770202637,8.87310028076172,8.88164043426514,8.89779281616211,8.92069435119629,8.9514217376709,8.99063873291016,9.03862285614014,9.09626388549805,9.16324329376221,9.23688983917236,9.31347846984863,9.39016819000244,9.46589183807373,9.54090690612793,9.61524677276611,9.68937587738037,9.76356506347656,9.83753299713135],"z":[0.74,0.48,0.46,0.49,0.55,0.36,0.43,0.37,0.57,0.43,0.3,0.26,0.3,0.24,0.23,0.27,0.09,0.09,0.2,0.13,0.13,0.17,0.16,0.15,0.19,0.18,0.15,0.12,0.18,0.21,0.31,0.19,0.16,0.2,0.16,0.16,0.12,0.16,0.17,0.24,0.18,0.09,0.06,0.15,0.12,0.1,0.18,0.6,0.94,0.75,0.58,0.74,0.77,0.72,0.68,0.51,0.57,0.44,0.29,0.33,0.27,0.31,0.33,0.31,0.23,0.14,0.26,0.25,1.24,1.26,1.1,1.09,1.04,0.85,0.79,0.8,0.99,0.88,0.89,0.86,0.67,0.76,0.63,0.79,0.7,0.96,0.87,0.67,0.67,0.59,0.71,0.64,0.5,0.54,0.59,0.55,0.48,0.51,0.54,0.69,0.59,0.51,0.59,0.53,0.51,0.41,0.47,0.34,0.44,0.51,0.63,0.75,0.58,0.38,0.58,0.85,0.38,0.45,0.24,0.55,0.42,0.27,0.47,0.31,0.19,0.2,0.21,0.27,0.14,0.2,0.18,0.2,0.09,0.22,0.2,0.17,0.22,1,0.7,0.72,0.15,0.19,0.12,0.1,0.13,0.1,0.12,0.11,0.08,0.07,0.07,0.09,0.06,0.07,0.08,0.07,0.05,0.06,0.23,0.31,0.27,0.29,0.3,0.21,0.24,0.28,0.32,0.24,0.11,0.19,0.17,0.22,0.11,0.11,0.16,0.2,0.22,0.05,0.09,0.11,0.18,0.21,0.27,0.38,0.27,0.22,0.17,0.26,0.26,0.25,0.27,0.21,0.17,0.19,0.13,0.17,0.17,0.14,0.12,0.13,0.12,0.13,0.08,0.86,0.66,0.78,0.43,0.64,0.62,0.58,0.38,0.35,0.57,0.21,0.32,0.44,0.57,0.41,0.26,0.33,0.3,0.28,0.2,0.18,0.44,0.37,0.29,0.26,0.25,0.26,0.25,0.2,0.21,0.19,0.17,0.16,0.22,0.21,0.2,0.22,0.21,0.2,0.12,0.14,0.08,0.06,0.08,0.12,0.06,0.07,0.05,0.06,0.06,0.1,0.04,0.05,0.03,0.04,0.05,0.02,0.04,0.02,0.02,0.59,0.68,0.59,0.56,0.42,0.3,0.46,0.37,0.45,0.31,0.55,0.55,0.59,0.51,0.53,0.51,0.6,0.3,0.19,0.03,0.33,0.44,0.25,0.08,0.32,0.5,0.2,0.5,0.63,0.32,0.38,0.52,0.35,0.24,0.3,0.21,0.21,0.37,0.36,0,0,0.34,0.33,0.32,0,0,0,0,0,0,0,0,0.3,1.66,0.96,0.81,0.83,0.76,0.64,0.52,0.51,0.6,0.8,0.7,0.44,0.45,0.41,0.36,0.34,0.33,0.36,0.3,0.23,0.29,0.36,0.55,0.5,0.47,0.56,0.51,0.57,0.5,0.46,0.41,0.39,0.26,0.24,0.23,0.25,0.2,0.29,0.29,0.17,0.24,0.18,0.16,1.28,1.33,1.31,1.27,0.69,0.6,0.38,0.65,0.64,0.54,0.7,0.64,0.76,0.33,0.41,0.28,0.48,0.18,0.26,0.27,0.24,0.18,0.33,0.12,0.16,0.28,0.34,0.25,0.21,0.18,0.2,0.17,0.12,0.14,0.23,0.15,0.24,0.19,0.2,0.17,0.23,0.26,0.32,0.26],"mode":"markers","type":"scatter3d","marker":{"colorbar":{"title":"cluster","ticklen":2},"cmin":1,"cmax":4,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":false,"color":[1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],"line":{"colorbar":{"title":"","ticklen":2},"cmin":1,"cmax":4,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":false,"color":[1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]}},"frame":null},{"x":[7356.4990234375,3643817.5],"y":[0.270150005817413,81.7156600952148],"type":"scatter3d","mode":"markers","opacity":0,"hoverinfo":"none","showlegend":false,"marker":{"colorbar":{"title":"cluster","ticklen":2,"len":0.5,"lenmode":"fraction","y":1,"yanchor":"top"},"cmin":1,"cmax":4,"colorscale":[["0","rgba(68,1,84,1)"],["0.0416666666666667","rgba(70,19,97,1)"],["0.0833333333333333","rgba(72,32,111,1)"],["0.125","rgba(71,45,122,1)"],["0.166666666666667","rgba(68,58,128,1)"],["0.208333333333333","rgba(64,70,135,1)"],["0.25","rgba(60,82,138,1)"],["0.291666666666667","rgba(56,93,140,1)"],["0.333333333333333","rgba(49,104,142,1)"],["0.375","rgba(46,114,142,1)"],["0.416666666666667","rgba(42,123,142,1)"],["0.458333333333333","rgba(38,133,141,1)"],["0.5","rgba(37,144,140,1)"],["0.541666666666667","rgba(33,154,138,1)"],["0.583333333333333","rgba(39,164,133,1)"],["0.625","rgba(47,174,127,1)"],["0.666666666666667","rgba(53,183,121,1)"],["0.708333333333333","rgba(79,191,110,1)"],["0.75","rgba(98,199,98,1)"],["0.791666666666667","rgba(119,207,85,1)"],["0.833333333333333","rgba(147,214,70,1)"],["0.875","rgba(172,220,52,1)"],["0.916666666666667","rgba(199,225,42,1)"],["0.958333333333333","rgba(226,228,40,1)"],["1","rgba(253,231,37,1)"]],"showscale":true,"color":[1,4],"line":{"color":"rgba(255,127,14,1)"}},"z":[0,1.66],"frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
Based on the PAM clustering, I decided to visualize the data in 3D; I chose the variables “rgdpna”, “value”, and “pop” for the axes based on the large differences observed in these variables when looking at the medoids. The “value” axis shows the rate of gun homicides per 100k people. Although there are some overlapping/similar points between the groupings, they appear to be decently grouped overall. In particular, the yellow group is very distinct from the others. It also appears that the clusters are based mainly on the population and real GDP axes; the value ranges between/across groups appear to be pretty similar.</p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
